version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      # - /app/node_modules
    environment:
      - REACT_APP_NAME=Inno-dev
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env